/**
 * ShapeMap generation: preserves SHACL target information (`sh:targetClass`,
 * `sh:targetSubjectsOf`, `sh:targetObjectsOf`) that has no ShEx equivalent,
 * as ShapeMap entries (https://shexspec.github.io/shape-map/).
 */
import type { Term } from '@rdfjs/types';
import type { Store } from 'n3';
import { parseShaclSchema } from './parse';

const XSD_STRING = 'http://www.w3.org/2001/XMLSchema#string';

/** A ShapeMap node for an `sh:targetNode` value (an IRI or a literal). */
function targetNodePattern(node: Term): string {
  if (node.termType !== 'Literal') {
    return `<${node.value}>`;
  }
  const escaped = node.value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  if (node.language !== '') {
    return `"${escaped}"@${node.language}`;
  }
  if (node.datatype.value !== XSD_STRING) {
    return `"${escaped}"^^<${node.datatype.value}>`;
  }
  return `"${escaped}"`;
}

/**
 * A ShapeMap entry that associates RDF nodes with shapes for validation.
 * Based on the ShapeMap specification: https://shexspec.github.io/shape-map/
 */
export interface ShapeMapEntry {
  /** The node pattern (e.g., "FOCUS rdf:type ex:Person") */
  node: string;
  /** The shape to validate against */
  shape: string;
}

/** A complete ShapeMap that can be used with ShEx validation. */
export interface ShapeMap {
  /** Array of node-shape associations */
  entries: ShapeMapEntry[];
}

/**
 * Extracts ShapeMap information from a SHACL dataset.
 *
 * Each `sh:targetClass`, `sh:targetSubjectsOf` and `sh:targetObjectsOf` on a
 * node shape produces one ShapeMap entry associating the targeted nodes with
 * that shape.
 */
export function shapeMapFromDataset(shapeStore: Store): ShapeMap {
  const entries: ShapeMapEntry[] = [];

  for (const shape of parseShaclSchema(shapeStore).shapes) {
    // A deactivated shape validates nothing, so it targets nothing.
    if (!shape.deactivated) {
      for (const targetClass of shape.targetClasses) {
        entries.push({ node: `FOCUS rdf:type <${targetClass}>`, shape: shape.id });
      }
      // The implicit class target: a node shape that is also an rdfs:Class
      // targets its own instances.
      if (shape.implicitClassTarget) {
        entries.push({ node: `FOCUS rdf:type <${shape.id}>`, shape: shape.id });
      }
      for (const node of shape.targetNodes) {
        entries.push({ node: targetNodePattern(node), shape: shape.id });
      }
      for (const predicate of shape.targetSubjectsOf) {
        entries.push({ node: `FOCUS <${predicate}> _`, shape: shape.id });
      }
      for (const predicate of shape.targetObjectsOf) {
        entries.push({ node: `_ <${predicate}> FOCUS`, shape: shape.id });
      }
    }
  }

  return { entries };
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Converts a ShapeMap object to its textual format.
 *
 * Note: the header comments and layout are load-bearing — existing consumers
 * and the fixture suite depend on this exact output.
 */
export function writeShapeMap(shapeMap: ShapeMap, prefixes?: Record<string, string>): string {
  if (shapeMap.entries.length === 0) {
    return '# No shape mappings found\n';
  }

  let output = '# @generated This file was generated by GitHub Copilot AI to test issue #283 resolution\n';
  output += '# ShapeMap - Associates RDF nodes with validation shapes\n';
  output += '# Based on: https://shexspec.github.io/shape-map/\n';
  output += '# Format: {node pattern}@{shape}\n\n';

  // Compile each prefix's IRI pattern once, not once per entry.
  const compactions = Object.entries(prefixes ?? {})
    .filter(([prefix]) => prefix && prefix !== 'base')
    .map(([prefix, iri]) => ({
      prefix,
      iri,
      pattern: new RegExp(`<${escapeRegExp(iri)}([^>]*)>`, 'g'),
    }));

  if (prefixes) {
    for (const { prefix, iri } of compactions) {
      output += `PREFIX ${prefix}: <${iri}>\n`;
    }
    output += '\n';
  }

  for (const entry of shapeMap.entries) {
    let nodePattern = entry.node;
    let shapeId = entry.shape;
    for (const { prefix, iri, pattern } of compactions) {
      nodePattern = nodePattern.replace(pattern, `${prefix}:$1`);
      shapeId = shapeId.replace(iri, `${prefix}:`);
    }
    output += `{${nodePattern}}@${shapeId}\n`;
  }

  return output;
}
